language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 1.0.4
before_script:
  - dotnet restore SofiAssignment.sln
script:  
  - dotnet build SofiAssignment.sln
after_success:
  - dotnet test SofiAssignment.Tests/SofiAssignment.Tests.csproj